name: maduro
description: "Fruit Ripeness Detection."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Existing dependencies
  camera: ^0.11.1
  gap: ^3.0.1
  external_path: ^2.2.0
  media_scanner: ^2.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_rating_bar: ^4.0.1
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  provider: ^6.1.4
  flutter_svg: ^2.0.9
  flutter_gif: ^0.0.4
  flutter_image: ^4.1.12
  carousel_slider: ^5.0.0
  google_mlkit_object_detection: ^0.15.0
  firebase_storage: ^13.0.1
  google_mlkit_commons: ^0.11.0
  tflite_flutter: ^0.11.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  firebase_vertexai: ^2.2.0
  google_generative_ai: ^0.4.7
  crypto: ^3.0.6
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  image_gallery_saver_plus: ^4.0.1
  google_fonts: ^6.3.1
  url_launcher: ^6.3.1
  
  # New dependencies for weather integration
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Klavika
      fonts:
        - asset: assets/fonts/KlavikaBoldBold.otf
    - family: Frutiger
      fonts:
        - asset: assets/fonts/FrutigerLTStd-Roman.otf